import { Planet, Zodiac } from "./astro";

export const MEANINGS: Record<Planet, Record<Zodiac, string>> = {
  Sun: {
    Aries: "Your core shines through bold action and fearless leadership.",
    Taurus:
      "Your essence is grounded, steady, and deeply connected to comfort.",
    Gemini: "Your spirit thrives on curiosity, conversation, and adaptability.",
    Cancer: "Your identity is tied to nurturing, home, and emotional bonds.",
    Leo: "Your core radiates creativity, confidence, and warmth.",
    Virgo: "Your essence is practical, detail-oriented, and service-minded.",
    Libra: "Your spirit seeks harmony, beauty, and balanced relationships.",
    Scorpio: "Your identity is intense, transformative, and deeply emotional.",
    Sagittarius: "Your essence craves adventure, truth, and boundless growth.",
    Capricorn:
      "Your core is ambitious, disciplined, and focused on achievement.",
    Aquarius:
      "Your spirit thrives on innovation, freedom, and community vision.",
    Pisces: "Your essence is compassionate, dreamy, and spiritually attuned.",
  },
  Moon: {
    Aries: "Your emotions are fiery, impulsive, and quick to react.",
    Taurus: "Your feelings are steady, comfort-loving, and sensual.",
    Gemini: "Your moods shift quickly, craving variety and communication.",
    Cancer: "You feel safe through family, nurturing, and emotional closeness.",
    Leo: "Your emotions are dramatic, generous, and seek recognition.",
    Virgo: "Your heart needs order, service, and practical solutions.",
    Libra: "You feel balanced when relationships are fair and harmonious.",
    Scorpio: "Your emotions run deep, intense, and transformative.",
    Sagittarius: "You find comfort in freedom, exploration, and optimism.",
    Capricorn:
      "Your feelings are controlled, responsible, and achievement-driven.",
    Aquarius:
      "You process emotions logically, craving independence and ideals.",
    Pisces: "Your moods are sensitive, intuitive, and deeply compassionate.",
  },
  Mercury: {
    Aries: "You communicate quickly, directly, and with bold ideas.",
    Taurus: "Your mind is steady, practical, and focused on security.",
    Gemini: "You think fast, love variety, and thrive on curiosity.",
    Cancer: "Your communication is emotional, intuitive, and protective.",
    Leo: "You speak with creativity, flair, and a need for recognition.",
    Virgo: "Your mind is analytical, precise, and detail-focused.",
    Libra: "You communicate with charm, balance, and diplomacy.",
    Scorpio: "You think deeply, probe beneath the surface, and value truth.",
    Sagittarius: "Your ideas are adventurous, philosophical, and expansive.",
    Capricorn: "Your mind is practical, disciplined, and achievement-driven.",
    Aquarius: "You communicate innovatively, uniquely, and with big vision.",
    Pisces: "Your thoughts are imaginative, intuitive, and poetic.",
  },
  Venus: {
    Aries: "You love boldly, passionately, and with spontaneity.",
    Taurus: "You value loyalty, comfort, and sensual pleasures in love.",
    Gemini: "You seek playful, lighthearted, and intellectual connections.",
    Cancer: "You love deeply, nurturingly, and protectively.",
    Leo: "You desire romance, creativity, and admiration in love.",
    Virgo: "You show love through service, care, and practical support.",
    Libra: "You value harmony, beauty, and balanced partnerships.",
    Scorpio: "You love intensely, passionately, and transformatively.",
    Sagittarius: "You seek freedom, adventure, and growth in relationships.",
    Capricorn: "You value loyalty, stability, and long-term commitments.",
    Aquarius: "You desire independence, uniqueness, and visionary love.",
    Pisces: "You love selflessly, compassionately, and with spiritual depth.",
  },
  Mars: {
    Aries: "You act boldly, quickly, and thrive on competition.",
    Taurus: "Your drive is steady, patient, and focused on security.",
    Gemini: "You pursue goals with versatility, wit, and mental energy.",
    Cancer: "You act protectively, emotionally, and indirectly.",
    Leo: "Your drive is fueled by pride, creativity, and self-expression.",
    Virgo: "You act with precision, practicality, and problem-solving.",
    Libra: "You pursue action through balance, charm, and cooperation.",
    Scorpio: "Your energy is intense, focused, and transformative.",
    Sagittarius: "You act with passion for freedom, growth, and exploration.",
    Capricorn: "Your drive is disciplined, ambitious, and goal-oriented.",
    Aquarius: "You act independently, rebelliously, and for collective ideals.",
    Pisces: "Your energy flows through creativity, intuition, and compassion.",
  },
  Jupiter: {
    Aries: "Your growth comes through courage, boldness, and initiative.",
    Taurus: "You expand through stability, patience, and material abundance.",
    Gemini: "Your opportunities come through curiosity, learning, and variety.",
    Cancer: "You grow through family, nurturing, and emotional bonds.",
    Leo: "You expand through creativity, leadership, and generosity.",
    Virgo: "Your growth comes through service, discipline, and practicality.",
    Libra: "You find luck in partnerships, harmony, and fairness.",
    Scorpio: "You expand through transformation, intensity, and depth.",
    Sagittarius: "You grow through adventure, truth, and higher wisdom.",
    Capricorn:
      "Your expansion comes through discipline, responsibility, and work.",
    Aquarius: "You find growth in innovation, freedom, and community vision.",
    Pisces: "You expand through compassion, spirituality, and imagination.",
  },
  Saturn: {
    Aries: "You face lessons in patience, discipline, and controlled action.",
    Taurus: "Your challenges involve security, patience, and material values.",
    Gemini: "You must learn focus, communication discipline, and consistency.",
    Cancer: "You face lessons in emotional responsibility and family ties.",
    Leo: "You learn discipline in self-expression, pride, and leadership.",
    Virgo: "Your lessons involve work, perfection, and humble service.",
    Libra:
      "You must master balance, fairness, and relationship responsibility.",
    Scorpio: "Your challenges involve control, transformation, and power.",
    Sagittarius:
      "You face lessons in truth, freedom, and philosophical structure.",
    Capricorn: "You thrive through discipline, ambition, and responsibility.",
    Aquarius: "You learn structure through innovation, ideals, and community.",
    Pisces: "Your lessons involve boundaries, compassion, and faith.",
  },
  Uranus: {
    Aries: "You bring sudden change through bold action and innovation.",
    Taurus: "You revolutionize values, comfort, and material stability.",
    Gemini: "You disrupt through ideas, curiosity, and new communication.",
    Cancer: "You innovate in home, family, and emotional traditions.",
    Leo: "You rebel creatively, dramatically, and with flair.",
    Virgo: "You innovate through health, service, and practical systems.",
    Libra: "You shake up relationships, harmony, and balance.",
    Scorpio: "You revolutionize intimacy, transformation, and power.",
    Sagittarius: "You innovate through freedom, truth, and exploration.",
    Capricorn: "You disrupt structures, authority, and traditions.",
    Aquarius: "You embody originality, freedom, and visionary ideals.",
    Pisces: "You innovate through spirituality, imagination, and compassion.",
  },
  Neptune: {
    Aries: "Your dreams spark bold action and fearless imagination.",
    Taurus: "You dream of stability, comfort, and earthly beauty.",
    Gemini: "Your imagination thrives on ideas, stories, and connections.",
    Cancer: "You dream of nurturing, emotional safety, and family bonds.",
    Leo: "Your fantasies are creative, dramatic, and self-expressive.",
    Virgo: "You imagine perfection, service, and spiritual practicality.",
    Libra: "Your dreams involve beauty, harmony, and idealized love.",
    Scorpio: "You envision transformation, passion, and emotional depth.",
    Sagittarius: "Your dreams involve truth, philosophy, and exploration.",
    Capricorn: "You dream through discipline, structure, and achievement.",
    Aquarius: "Your imagination is futuristic, collective, and visionary.",
    Pisces: "You embody spiritual compassion, intuition, and dreamlike flow.",
  },
};
